</section>
<footer>
            <div class="cright">
                <p>&copy;2013 AntiТренинги</p>
                <p>Система доведения учеников до результата</p>
            </div>
            <div class="logo">
                <p>РАЗРАботано</p>
                <a href=""><img src="/images/logo-off.png" alt=""><img class="logo-on" src="/images/logo-on.png" alt=""></a>
            </div>
        </footer>
       </div></body>